/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MePersonRouteImport } from './routes/me.$person'
import { Route as PhonePersonRouteImport } from './routes/phone.$person'
import { Route as MePersonUpdateRouteImport } from './routes/me.$person.update'
import { Route as PhonePersonIndexRouteImport } from './routes/phone.$person.index'
import { Route as PhonePersonAppRouteImport } from './routes/phone.$person.$app'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MePersonRoute = MePersonRouteImport.update({
  id: '/me/$person',
  path: '/me/$person',
  getParentRoute: () => rootRouteImport,
} as any)
const PhonePersonRoute = PhonePersonRouteImport.update({
  id: '/phone/$person',
  path: '/phone/$person',
  getParentRoute: () => rootRouteImport,
} as any)
const MePersonUpdateRoute = MePersonUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => MePersonRoute,
} as any)
const PhonePersonIndexRoute = PhonePersonIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PhonePersonRoute,
} as any)
const PhonePersonAppRoute = PhonePersonAppRouteImport.update({
  id: '/$app',
  path: '/$app',
  getParentRoute: () => PhonePersonRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/me/$person': typeof MePersonRouteWithChildren
  '/phone/$person': typeof PhonePersonRouteWithChildren
  '/me/$person/update': typeof MePersonUpdateRoute
  '/phone/$person/$app': typeof PhonePersonAppRoute
  '/phone/$person/': typeof PhonePersonIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/me/$person': typeof MePersonRouteWithChildren
  '/me/$person/update': typeof MePersonUpdateRoute
  '/phone/$person/$app': typeof PhonePersonAppRoute
  '/phone/$person': typeof PhonePersonIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/me/$person': typeof MePersonRouteWithChildren
  '/phone/$person': typeof PhonePersonRouteWithChildren
  '/me/$person/update': typeof MePersonUpdateRoute
  '/phone/$person/$app': typeof PhonePersonAppRoute
  '/phone/$person/': typeof PhonePersonIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/me/$person'
    | '/phone/$person'
    | '/me/$person/update'
    | '/phone/$person/$app'
    | '/phone/$person/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/me/$person'
    | '/me/$person/update'
    | '/phone/$person/$app'
    | '/phone/$person'
  id:
    | '__root__'
    | '/'
    | '/me/$person'
    | '/phone/$person'
    | '/me/$person/update'
    | '/phone/$person/$app'
    | '/phone/$person/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MePersonRoute: typeof MePersonRouteWithChildren
  PhonePersonRoute: typeof PhonePersonRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/$person': {
      id: '/me/$person'
      path: '/me/$person'
      fullPath: '/me/$person'
      preLoaderRoute: typeof MePersonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone/$person': {
      id: '/phone/$person'
      path: '/phone/$person'
      fullPath: '/phone/$person'
      preLoaderRoute: typeof PhonePersonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/$person/update': {
      id: '/me/$person/update'
      path: '/update'
      fullPath: '/me/$person/update'
      preLoaderRoute: typeof MePersonUpdateRouteImport
      parentRoute: typeof MePersonRoute
    }
    '/phone/$person/': {
      id: '/phone/$person/'
      path: '/'
      fullPath: '/phone/$person/'
      preLoaderRoute: typeof PhonePersonIndexRouteImport
      parentRoute: typeof PhonePersonRoute
    }
    '/phone/$person/$app': {
      id: '/phone/$person/$app'
      path: '/$app'
      fullPath: '/phone/$person/$app'
      preLoaderRoute: typeof PhonePersonAppRouteImport
      parentRoute: typeof PhonePersonRoute
    }
  }
}

interface MePersonRouteChildren {
  MePersonUpdateRoute: typeof MePersonUpdateRoute
}

const MePersonRouteChildren: MePersonRouteChildren = {
  MePersonUpdateRoute: MePersonUpdateRoute,
}

const MePersonRouteWithChildren = MePersonRoute._addFileChildren(
  MePersonRouteChildren,
)

interface PhonePersonRouteChildren {
  PhonePersonAppRoute: typeof PhonePersonAppRoute
  PhonePersonIndexRoute: typeof PhonePersonIndexRoute
}

const PhonePersonRouteChildren: PhonePersonRouteChildren = {
  PhonePersonAppRoute: PhonePersonAppRoute,
  PhonePersonIndexRoute: PhonePersonIndexRoute,
}

const PhonePersonRouteWithChildren = PhonePersonRoute._addFileChildren(
  PhonePersonRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MePersonRoute: MePersonRouteWithChildren,
  PhonePersonRoute: PhonePersonRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
